print ('My name is Seunfunmi Adegoke' )
print()
print ('This is my attempt at learning how to code')
print()
print('I have decided to do this by committing to the #DevCUyo 30 days of code challenge')
print()
print ('It is great having a comunity to learn with')
print()
print('I am looking forward to day 2 :-)')
